version: '3.7'
services:

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres


  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    environment:
      - server.port=8761

  gateway:
    build: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/


  # book-service
  book-service:
    build: ./book-service
    ports:
      - "9560:9560"
    depends_on:
      - db
      - discovery-service
    environment:
      - server.port=9560
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # rating-service
  rating-service:
    build: ./rating-service
    ports:
      - "9009:9009"
    depends_on:
      - db
      - discovery-service
    environment:
      - server.port=9009
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
